version: '3.1'

services:
   mymongo:
    image: mongo:4.0.4
    container_name: mymongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tal
      MONGO_INITDB_ROOT_PASSWORD: cybereason
      MONGO_INITDB_DATABASE: cr-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_init/:/docker-entrypoint-initdb.d
      - ./data_files/:/data_files/
